### ISSUE TITLE
Unquoted SQL keyword columns failing on INSERT

### ISSUE THREAD

**Issue by remotelyliving** [behance/nbd.php-dbal#25]
this guy https://github.com/behance/nbd.php-dbal/blob/master/src/Adapters/PdoAdapter.php#L35

could probably benefit from something like this: 

```$columns_sql   = '`' . implode( '`, `', $columns ) . '`'```

**Comment by remotelyliving** [comment]
A prime example would be insert a gatekeeper rule. Two of the columns are SQL keywords, `type` and `key`.

**Comment by bryanlatten** [comment]
haha, those protected words...
